In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[2,3,4,5]])
a.shape




(2, 4)

In [ ]:

a = np.arrange(6).reshape(2,3)

python is more faster than nmpy , if sample size is more at that case numpy is grater
3d==tensor


In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.array([[1,6,7,8],[6,7,8,9]])
a

array([[1, 6, 7, 8],
       [6, 7, 8, 9]])

In [ ]:
b = np.array([[3,4,5,6],[5,6,7,8]])
b

array([[3, 4, 5, 6],
       [5, 6, 7, 8]])

In [ ]:
d = np.concatenate((a,b), axis=1)
d

array([[1, 6, 7, 8, 3, 4, 5, 6],
       [6, 7, 8, 9, 5, 6, 7, 8]])

#another way of concatenate
d = np.stack((a,b), axis=1)
d

In [ ]:
d = np.vstack((a,b))
d

array([[1, 6, 7, 8],
       [6, 7, 8, 9],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [ ]:
d = np.hstack((a,b))
d

array([[1, 6, 7, 8, 3, 4, 5, 6],
       [6, 7, 8, 9, 5, 6, 7, 8]])

###                                                                                                                                                     Worksheet1

In [ ]:
#Initialize an empty array with size 2X2.
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
#2. Initialize an all one array with size 4X2.
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
a = np.full((3,2),5)
a


array([[5, 5],
       [5, 5],
       [5, 5]])

In [ ]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = np.zeros_like((4,2))
a

array([0, 0])

In [ ]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
a = np.ones_like((4,2))
a

array([1, 1])

In [ ]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = np.array([[1,2,3,4]])
new_list

array([[1, 2, 3, 4]])

In [ ]:
#Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
n = np.arange(1,50)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
#2. Create a 3X3 matrix with values ranging from 0 to 8.
a = np.array([[[1,6,7],[6,7,8],[4,5,6]]])
a.reshape(3,3)

array([[1, 6, 7],
       [6, 7, 8],
       [4, 5, 6]])

In [ ]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
a = np.eye
a

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

In [ ]:
#4 Create a random array of size 30 and find the mean of the array.
a = np.random.random(30)
b = a.mean()
b

0.5436557666954693

In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
a = np.random.random((10,10))
b=a.min()
c=a.max()
print(b,c)

0.0001709445253568198 0.9921076163503983


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].
a = np.array([1,2,3,4])
b = a[::-1]
b

array([4, 3, 2, 1])

In [ ]:
# 8 Create a 2d array with 1 on border and 0 inside.
import numpy as np
a = np.zeros((6, 6), dtype=int)
a[0, :] = 1  # Top border
a[-1, :] = 1  # Bottom
a[:, 0] = 1  # Left
a[:, -1] = 1  #right


print("2D array with border 1 and inside 0:")
print(a)


2D array with border 1 and inside 0:
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:

#9. Create an 8x8 checkerboard matrix
c = np.zeros((8, 8), dtype=int)
c[1::2, ::2] = 1  # Odd rows: 1 in even columns
c[::2, 1::2] = 1  # Even rows: 1 in odd columns

print(c)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Problem - 3: Array Operations:
#1. Add the two array.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
add = x + y
print("Add of x and y:\n", add)


Add of x and y:
 [[ 6  8]
 [10 13]]


In [ ]:
#2.subtract the two array
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
sub = x - y
print("sub of x and y:\n", sub)

sub of x and y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
#3. Multiply the array with any integers of your choice.
mul = x * 3
print("Multiplication of x by 3:\n", mul)



Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]


In [ ]:
#4. Find the square of each element of the array.
square = x ** 2
print("Square of each element in x:\n", square)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)


Dot product of v and w: 219


In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
concat_ab = np.concatenate((a, b), axis=0)
print("Concatenate a and b along rows:\n", concat_ab)



Concatenate a and b along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

import numpy as np
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])
v_reshaped = v.reshape(1, -1)
concat_xv = np.concatenate((x, v_reshaped), axis=0)
print("Concatenated x and v:\n", concat_xv)


Concatenated x and v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


The error occurs because x is a 2D array with two columns, while v is a 1D array with no explicit column dimension.
Concatenation along axis=0 (row-wise) requires all arrays to have the same number of columns, which is not satisfied here

#Problem - 4: Matrix Operations:
For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])

A_inv = np.linalg.inv(A)  # Calculate the inverse of A
I = np.dot(A, A_inv)    # Multiply A by its inverse
print("A * A⁻¹ =\n", I)


A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
import numpy as np

# Define matrix A and matrix B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Matrix multiplication AB
AB = np.dot(A, B)

# Matrix multiplication BA
BA = np.dot(B, A)

# Print the results
print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [ ]:
import numpy as np

# Define matrix A and matrix B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Matrix multiplication AB
AB = np.dot(A, B)

# Transpose of AB
AB_T = np.transpose(AB)

# Compute Bᵀ * Aᵀ
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

# Print the results
print("(AB)ᵀ =\n", AB_T)
print("Bᵀ * Aᵀ =\n", B_T_A_T)


(AB)ᵀ =
 [[23 51]
 [13 29]]
Bᵀ * Aᵀ =
 [[23 51]
 [13 29]]


In [ ]:
# Define matrix A and vector B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv (Inverse Method)
X = np.dot(np.linalg.inv(A), B)

print("Solution for X (x, y, z):", X)


Solution for X (x, y, z): [ 2.  1. -2.]


In [ ]:
# Solve for X using np.linalg.solve (alternative method)
X_solve = np.linalg.solve(A, B)

print("Solution using np.linalg.solve:", X_solve)


Solution using np.linalg.solve: [ 2.  1. -2.]
